name: CI/CD for sam app

on: 
    push: 
        branches: [deploy]
    workflow_dispatch: 

permissions:
    id-token: write
    contents: write

jobs:
    build_and_deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup AWS CLI
              uses: aws-actions/configure-aws-credentials@v3 
              with: 
                aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ap-northeast-1

            - name: Install dependencies
              run: 
                chmod +x dependency.sh
                ./dependency.sh

            - name: Build Project
              run: 
                chmod +x commands.sh
                ./commands.sh

